version: "2"

services:
    # Core configuration
    nginx:
        container_name: ${CONTAINER_NAME}_nginx
        image: nginx:1.13-alpine
        ports:
            - '${NGINX_PORT}:80'
        volumes:
            - './:${WORKPATH}:rw'
            - './docker/nginx/conf/core.conf:/etc/nginx/conf/nginx.conf:rw'
            - './docker/nginx/conf/development:/etc/nginx/conf.d:rw'
            # - './docker/nginx/conf/production:/etc/nginx/conf.d:ro'
            - './docker/nginx/logs/:/var/log/nginx'
        restart: always

    php-fpm:
        container_name: ${CONTAINER_NAME}_php-fpm
        build: './docker/php'
        environment:
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
            BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID}'
            BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN}'
        ports:
            - '${PHP_PORT}:9000'
        volumes:
            - './:${WORKPATH}:rw'
            - './docker/php/logs:/tmp:rw'
        restart: always

    # Server optimization
    varnish:
        container_name: ${CONTAINER_NAME}_varnish
        build: './docker/varnish'
        volumes:
            - './:${WORKPATH}:rw'
            - './docker/varnish/conf:/etc/varnish:rw'
        ports:
            - '${VARNISH_PORT}:80'
        restart: always

    redis:
        container_name: ${CONTAINER_NAME}_redis
        image: redis
        ports:
            - '${REDIS_PORT}:6379'
        restart: always

    # DB configuration
    mysql:
        container_name: ${CONTAINER_NAME}_mysql
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        restart: always

    # Performances configuration
    blackfire:
        container_name: ${CONTAINER_NAME}_blackfire
        image: blackfire/blackfire
        environment:
            BLACKFIRE_SERVER_ID: '${BLACKFIRE_SERVER_ID}'
            BLACKFIRE_SERVER_TOKEN: '${BLACKFIRE_SERVER_TOKEN}'
            BLACKFIRE_CLIENT_ID: '${BLACKFIRE_CLIENT_ID}'
            BLACKFIRE_CLIENT_TOKEN: '${BLACKFIRE_CLIENT_TOKEN}'
        links:
            - php-fpm
        volumes:
            - './:${WORKPATH}:rw'
        restart: always

volumes:
    mysql:
