<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function getDone()
    {
        $query = $this->createQueryBuilder('task')
            ->where('task.isDone = true')
            ->orderBy('task.createdAt', 'DESC')
            ->getQuery()
        ;

        $query->useQueryCache(true);
        $query->useResultCache(true);
        $query->setResultCacheLifetime(3600);

        return $query->getResult();
    }

    public function getTodo()
    {
        $query = $this->createQueryBuilder('task')
            ->where('task.isDone = false')
            ->orderBy('task.createdAt', 'DESC')
            ->getQuery()
        ;

        $query->useQueryCache(true);
        $query->useResultCache(true);
        $query->setResultCacheLifetime(3600);

        return $query->getResult();
    }
}
