imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver: '%env(DB_DRIVER_TEST)%'
        server_version: '%env(DB_VERSION_TEST)%'
        charset: '%env(DB_CHARSET_TEST)%'
        memory: true
        url: '%env(resolve:DATABASE_URL_TEST)%'

    # TODO Configure mapping
