AppBundle\Entity\Task:
    type: entity
    repositoryClass: AppBundle\Repository\TaskRepository
    table: task
    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO

    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: tasks

    fields:
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: created_at
        title:
            type: string
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        content:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        isDone:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            column: is_done
    lifecycleCallbacks: {  }
