AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Repository\UserRepository
    table: user

    oneToMany:
        tasks:
            targetEntity: AppBundle\Entity\Task
            mappedBy: user

    id:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: AUTO

    fields:
        username:
            type: string
            scale: 0
            length: 25
            unique: true
            nullable: false
            precision: 0
        password:
            type: string
            scale: 0
            length: 64
            unique: false
            nullable: false
            precision: 0
        email:
            type: string
            scale: 0
            length: 60
            unique: true
            nullable: false
            precision: 0
        roles:
            type: array
            unique: false
            nullable: false

    lifecycleCallbacks: {  }
